//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Database
{
    using System;
    using System.Collections.Generic;

    public partial class customer
    {
        public long id { get; set; }
        public string name1 { get; set; }
        public string name2 { get; set; }
        public string nric1 { get; set; }
        public string nric2 { get; set; }
        public string block_no { get; set; }
        public string job_site { get; set; }
        public string address { get; set; }
        public string contact_person { get; set; }
        public string email { get; set; }
        public string phone { get; set; }
        public string mobile { get; set; }
        public Nullable<bool> gst_registered { get; set; }
        public string gst_no { get; set; }

        public int? SourceOfEnquiry { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public System.DateTime modified_date { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public bool isactive { get; set; }
        public Nullable<int> zip_code { get; set; }
        public string unit_code { get; set; }
        public int branch_id { get; set; }
        public long CountryId { get; set; }
        public string CountryName { get; set; }
    }
}
