//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class loan
    {
        public int Id { get; set; }
        public int branch_Id { get; set; }
        public System.DateTime LoanDate { get; set; }
        public int rec_type { get; set; }
        public long person_id { get; set; }
        public string person_type { get; set; }
        public string purpose { get; set; }
        public int payment_mode { get; set; }
        public Nullable<int> bank_id { get; set; }
        public Nullable<int> cheque_number { get; set; }
        public decimal amount { get; set; }
        public System.Guid created_by { get; set; }
        public System.DateTime created_on { get; set; }
        public System.Guid updated_by { get; set; }
        public System.DateTime updated_on { get; set; }
        public bool isactive { get; set; }
        public Nullable<int> project_id { get; set; }
        public bool Verified { get; set; }
    }
}
