//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class payment_details_description
    {
        public long id { get; set; }
        public int payment_id { get; set; }
        public string description { get; set; }
        public decimal amount { get; set; }
        public Nullable<System.DateTime> created_date { get; set; }
    }
}
