//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class project
    {
        public long id { get; set; }
        public Nullable<System.DateTime> contract_date { get; set; }
        public string project_number { get; set; }
        public string project_name { get; set; }
        public string project_id { get; set; }
        public Nullable<System.DateTime> project_start_date { get; set; }
        public Nullable<long> salesmen_id { get; set; }
        public Nullable<long> branch_id { get; set; }
        public long customer_id { get; set; }
        public Nullable<decimal> contract_amount { get; set; }
        public Nullable<decimal> gst_percentage { get; set; }
        public Nullable<decimal> gst_amount { get; set; }
        public Nullable<decimal> total_amount { get; set; }
        public int bank_id { get; set; }
        public int status_id { get; set; }
        public string remarks { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public System.DateTime modified_date { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public bool isactive { get; set; }
        public Nullable<decimal> saleman_commission { get; set; }
    
        public virtual project projects1 { get; set; }
        public virtual project project1 { get; set; }
    }
}
