//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PMS.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class receipt
    {
        public long id { get; set; }
        public Nullable<System.DateTime> receipt_date { get; set; }
        public Nullable<long> project_id { get; set; }
        public Nullable<int> mode_of_payment_id { get; set; }
        public Nullable<int> bank_id { get; set; }
        public string cheque_details { get; set; }
        public Nullable<decimal> amount { get; set; }
        public Nullable<long> sales_man_id { get; set; }
        public Nullable<long> branch_id { get; set; }
        public string remarks { get; set; }
        public System.DateTime created_date { get; set; }
        public Nullable<System.Guid> created_by { get; set; }
        public System.DateTime modified_date { get; set; }
        public Nullable<System.Guid> modified_by { get; set; }
        public bool isactive { get; set; }
        public Nullable<decimal> gst_percentage { get; set; }
        public Nullable<decimal> gst_amount { get; set; }
        public Nullable<decimal> total_amount { get; set; }
    }
}
